

see sample run.

```
---------------------------------------------------------------
23.96.178.199 - NCUS SQL
104.42.238.205/ 13.86.216.196 - WUS SQL
--------------------------------------------------------------- experiment#1 with MultiSubnetFailover=false;
--failover to WUS initiated at 00:24
--failover to NCUS initiated at 00:25
start
RefreshDNS = False
SqlConnectionStringFile = connections.txt
SqlConnectionStringList = ***
EnableDnsRoundRobin = False
DnsRefreshTimeout = 120000
[2022-07-08T00:20:29.3596463Z] RefreshDBConnections: newConct, testabinaafailover1.database.windows.net, 23.96.178.199
[2022-07-08T00:20:29.4077992Z] RefreshDBConnections: newConct, testabinaafailover1.secondary.database.windows.net, 13.86.216.196
[2022-07-08T00:20:50.7760777Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:21:01.0613725Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:21:52.1737747Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:22:02.3802570Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:22:32.8881699Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:23:03.8372650Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:23:34.5013333Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:23:44.7905914Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:24:15.3644155Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:24:15.9846316Z] HandleExceptionForResiliency - ClearPool
[2022-07-08T00:24:15.9881429Z] HandleExceptionForResiliency - CloseConnection
[2022-07-08T00:24:26.3293074Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 13.86.216.196, x23.96.178.199
[2022-07-08T00:24:26.3800383Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 23.96.178.199, x104.42.238.205
[2022-07-08T00:24:36.7626926Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 23.96.178.199, x13.86.216.196
[2022-07-08T00:24:46.9764217Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 104.42.238.205, x23.96.178.199
[2022-07-08T00:24:57.1386505Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 23.96.178.199, x104.42.238.205
[2022-07-08T00:25:07.2681623Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 104.42.238.205, x23.96.178.199
[2022-07-08T00:25:27.6072111Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:25:38.3016338Z] HandleExceptionForResiliency - ClearPool
[2022-07-08T00:25:38.3019474Z] HandleExceptionForResiliency - CloseConnection
[2022-07-08T00:25:48.9498991Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 23.96.178.199, x13.86.216.196
[2022-07-08T00:25:48.9874902Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:25:59.6071895Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:26:20.0499335Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:26:41.2405476Z] RefreshDBConnections: exDnsRef, testabinaafailover1.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:26:52.3016059Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:27:13.4787486Z] RefreshDBConnections: exDnsRef, testabinaafailover1.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:27:24.5336400Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:27:45.7011736Z] RefreshDBConnections: exDnsRef, testabinaafailover1.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:27:56.7612527Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:28:17.9370923Z] RefreshDBConnections: exDnsRef, testabinaafailover1.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:28:28.9946991Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:28:50.1695674Z] RefreshDBConnections: exDnsRef, testabinaafailover1.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:29:01.2406253Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:29:11.4882805Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x23.96.178.199
[2022-07-08T00:31:24.5650912Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:31:34.7514435Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205

--------------------------------------------------------------- experiment#2 with MultiSubnetFailover=true;
--failover to NCUS initiated at 23:03
--failover to WUS initiated at 00:15
--failover to NCUS initiated at 00:18
start
SqlConnectionStringFile = connectionsMultiSubnetFailover.txt
SqlConnectionStringList = *** with MultiSubnetFailover=true;
EnableDnsRoundRobin = False
DnsRefreshTimeout = 120000
[2022-07-08T00:10:31.8927343Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:10:52.3891656Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 23.96.178.199, x13.86.216.196
[2022-07-08T00:11:03.3648119Z] HandleExceptionForResiliency - ClearPool
[2022-07-08T00:11:03.3683817Z] HandleExceptionForResiliency - CloseConnection
[2022-07-08T00:11:13.4973278Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:11:24.6621290Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:11:34.8092755Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:11:44.9802634Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:11:55.1575150Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:12:05.3469196Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:12:15.6269591Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x23.96.178.199
[2022-07-08T00:12:36.1157623Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:12:46.3507966Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:12:56.6100956Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:13:17.0235737Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:13:27.1922278Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:14:38.6326782Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:14:48.8451174Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:15:09.3478753Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:15:10.1253775Z] HandleExceptionForResiliency - ClearPool
[2022-07-08T00:15:10.1256807Z] HandleExceptionForResiliency - CloseConnection
[2022-07-08T00:15:20.5168907Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:15:20.9674233Z] HandleExceptionForResiliency - ClearPool
[2022-07-08T00:15:20.9676667Z] HandleExceptionForResiliency - CloseConnection
[2022-07-08T00:15:31.1124332Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 13.86.216.196, x23.96.178.199
[2022-07-08T00:15:31.1260599Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:15:41.4601771Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:15:51.5910864Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 23.96.178.199, x13.86.216.196
[2022-07-08T00:15:51.6068549Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:16:01.7312996Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 13.86.216.196, x23.96.178.199
[2022-07-08T00:16:01.7458091Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:16:12.0038599Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 23.96.178.199, x104.42.238.205
[2022-07-08T00:16:22.0878432Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:16:52.5270798Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:17:12.8681879Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:17:23.1335543Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:17:33.2782884Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:17:53.7508107Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 13.86.216.196, x104.42.238.205
[2022-07-08T00:18:14.1270082Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 104.42.238.205, x13.86.216.196
[2022-07-08T00:18:14.5449830Z] HandleExceptionForResiliency - ClearPool
[2022-07-08T00:18:14.5452722Z] HandleExceptionForResiliency - CloseConnection
[2022-07-08T00:18:25.2809516Z] RefreshDBConnections: failover, testabinaafailover1.database.windows.net, 23.96.178.199, x104.42.238.205
[2022-07-08T00:18:25.2947261Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:18:35.8967214Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:18:46.1129702Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:18:56.3159200Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:19:06.4713307Z] RefreshDBConnections: exDnsRef, testabinaafailover1.secondary.database.windows.net, System.AggregateException: One or more errors occurred. (No such host is known.) #N#  ---> System.Net.Sockets.SocketException (11001): No such host is known. #N#    at System.Net.Dns.HostResolutionEndHelper(IAsyncResult asyncResult) #N#    at System.Net.Dns.EndGetHostEntry(IAsyncResult asyncResult) #N#    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization) #N# --- End of stack trace from previous location where exception was thrown --- #N#    at ScratchApp1.SqlDnsTest.GetHostEntryAsync(String hostName) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 156 #N#    --- End of inner exception stack trace --- #N#    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification) #N#    at ScratchApp1.SqlDnsTest.DNSRefresh(String connectionString) in C:\Users\abinaa\source\repos\ScratchApp1\ScratchApp1\SqlDnsTest.cs:line 126
[2022-07-08T00:19:16.7449801Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 13.86.216.196, x23.96.178.199
[2022-07-08T00:19:26.9166418Z] RefreshDBConnections: failover, testabinaafailover1.secondary.database.windows.net, 104.42.238.205, x13.86.216.196
---------------------------------------------------------------
```
